# 元信息
[meta]
title = "骰娘寻访"
author = "整理者:暮星(1009592348) 编写者:一云(3443952316) 插图版本:莫一(1280432720) 骰子提供:所有参与的master(如有需要加入，请联系编写者，在线表格：【腾讯文档】骰娘寻访：https://docs.qq.com/sheet/DVHJ3V1JYUHVzQnZV?tab=BB08J2)"
date = 2023-10-01
version = "1.3"
update_urls = [
    "https://raw.githubusercontent.com/MX-fox/draw/main/%E9%AA%B0%E5%A8%98%E5%AF%BB%E8%AE%BF%EF%BC%88%E5%A4%8D%E6%9D%82%E7%89%8C%E5%A0%86%EF%BC%89.toml",
    "https://ghproxy.com/https://raw.githubusercontent.com/MX-fox/draw/main/%E9%AA%B0%E5%A8%98%E5%AF%BB%E8%AE%BF%EF%BC%88%E5%A4%8D%E6%9D%82%E7%89%8C%E5%A0%86%EF%BC%89.toml"
]

[decks]
 "随机骰娘寻访" = ["随着600个神秘玉石的消失，漆黑的包裹里透露出光芒\n#{DRAW-骰娘寻访}",]
 "海豹寻访" = ["随着600个神秘玉石的消失，漆黑的包裹里透露出光芒\n#{DRAW-海豹}",]
 "溯洄寻访" = ["随着600个神秘玉石的消失，漆黑的包裹里透露出光芒\n#{DRAW-溯洄}",]
 "青果寻访" = ["随着600个神秘玉石的消失，漆黑的包裹里透露出光芒\n#{DRAW-青果}",]
 "惠惠寻访" = ["随着600个神秘玉石的消失，漆黑的包裹里透露出光芒\n#{DRAW-惠惠}",]

# 复杂牌组
["骰娘寻访"]
# 是否导出
export = false
# key是否可见
visible = false
# 开启云内容
cloud_extra = true
# 云内容与本地内容去重
dictinct = true
# 云内容链接
options_urls = [
    "https://ghproxy.com/https://raw.githubusercontent.com/MX-fox/draw/main/%E6%B5%B7%E8%B1%B9%E5%AF%BB%E8%AE%BF.json",
    "https://ghproxy.com/https://raw.githubusercontent.com/MX-fox/draw/main/%E6%83%A0%E6%83%A0%E5%AF%BB%E8%AE%BF.json",
    "https://ghproxy.com/https://raw.githubusercontent.com/MX-fox/draw/main/%E6%BA%AF%E6%B4%84%E5%AF%BB%E8%AE%BF.json",
    "https://ghproxy.com/https://raw.githubusercontent.com/MX-fox/draw/main/%E9%9D%92%E6%9E%9C%E5%AF%BB%E8%AE%BF.json"
]


# 复杂牌组
["海豹"]
# 是否导出
export = false
# key是否可见
visible = false
# 开启云内容
cloud_extra = true
# 云内容与本地内容去重
dictinct = true
# 云内容链接
options_urls = ["https://ghproxy.com/https://raw.githubusercontent.com/MX-fox/draw/main/%E6%B5%B7%E8%B1%B9%E5%AF%BB%E8%AE%BF.json"]

# 复杂牌组
["惠惠"]
# 是否导出
export = false
# key是否可见
visible = false
# 开启云内容
cloud_extra = true
# 云内容与本地内容去重
dictinct = true
# 云内容链接
options_urls = ["https://ghproxy.com/https://raw.githubusercontent.com/MX-fox/draw/main/%E6%83%A0%E6%83%A0%E5%AF%BB%E8%AE%BF.json"]

# 复杂牌组
["溯洄"]
# 是否导出
export = false
# key是否可见
visible = false
# 开启云内容
cloud_extra = true
# 云内容与本地内容去重
dictinct = true
# 云内容链接
options_urls = ["https://ghproxy.com/https://raw.githubusercontent.com/MX-fox/draw/main/%E6%BA%AF%E6%B4%84%E5%AF%BB%E8%AE%BF.json"]

# 复杂牌组
["青果"]
# 是否导出
export = false
# key是否可见
visible = false
# 开启云内容
cloud_extra = true
# 云内容与本地内容去重
dictinct = true
# 云内容链接
options_urls = ["https://ghproxy.com/https://raw.githubusercontent.com/MX-fox/draw/main/%E9%9D%92%E6%9E%9C%E5%AF%BB%E8%AE%BF.json"]
